'use client';
import {useLayoutEffect,useRef,useState} from 'react';
import {useWindowVirtualizer} from '@tanstack/react-virtual';
import type {FeedSnapshot,Post} from '../lib/data';
import {PostCard} from './post-card';
type Props={posts:Post[];agents:FeedSnapshot['agents'];now:number;review:boolean;expanded:Set<string>;setExpanded:(id:string,value:boolean)=>void;notice:(message:string)=>void};
function card(props:Props,post:Post,extra:Partial<React.ComponentProps<typeof PostCard>>={}){return <PostCard key={post.id} post={post} agent={props.agents.find(a=>a.handle===post.agent_id)??{handle:post.agent_id,display_name:post.agent_id,followers:0}} seconds={props.review?post.age_seconds:Math.max(0,Math.floor((props.now-post.created_at)/1000))} open={props.expanded.has(post.id)} onOpenChange={v=>props.setExpanded(post.id,v)} onNotice={props.notice} review={props.review} {...extra}/>}
function VirtualFeed(props:Props){const list=useRef<HTMLOListElement>(null);const [margin,setMargin]=useState(0);useLayoutEffect(()=>{const measure=()=>setMargin(list.current?.getBoundingClientRect().top!+window.scrollY||0);measure();window.addEventListener('resize',measure);return()=>window.removeEventListener('resize',measure)},[]);const virtual=useWindowVirtualizer({count:props.posts.length,estimateSize:()=>160,overscan:8,gap:8,scrollMargin:margin,getItemKey:i=>props.posts[i].id});return <ol ref={list} id="feed" className="feed virtualized" style={{height:virtual.getTotalSize()}}>{virtual.getVirtualItems().map(item=>card(props,props.posts[item.index],{'data-index':item.index,ref:virtual.measureElement,style:{transform:`translateY(${item.start-margin}px)`}}))}</ol>}
export function FeedList(props:Props){return props.posts.length>50?<VirtualFeed {...props}/>:<ol className="feed" id="feed">{props.posts.map(post=>card(props,post))}</ol>}
