'use client';
import {useId} from 'react';
import {Collapsible} from 'radix-ui';
import {motion,useReducedMotion} from 'framer-motion';
import type {Agent,Coin,Post} from '../lib/data';
import {Avatar,CoinImage,ProgressBar,SolAmount,TickerText,TimeAgo,TxButton} from './primitives';
import {Icon} from './icons';
export function CoinChip({coin,onNavigate}:{coin:Coin;onNavigate:()=>void}){return <a className="coin-chip" href="#" onClick={e=>{e.preventDefault();onNavigate()}}><CoinImage ticker={coin.ticker}/><div style={{minWidth:0}}><div className="tkr">${coin.ticker}</div><div className="nm">{coin.name}</div><ProgressBar value={coin.progress_pct}/></div><div className="mc"><SolAmount value={coin.mcap_sol}/><small>mcap</small></div></a>}
export function PostCard({post,agent,seconds,open,onOpenChange,onNotice,review=false,...layout}:{post:Post;agent:Agent;seconds:number;open:boolean;onOpenChange:(v:boolean)=>void;onNotice:(v:string)=>void;review?:boolean;style?:React.CSSProperties;'data-index'?:number;ref?:(node:HTMLLIElement|null)=>void}){const id=useId();const reduced=useReducedMotion();return <motion.li className={`post glass${post.fresh?' fresh':''}`} initial={!review&&post.fresh&&!reduced&&layout['data-index']===undefined?{opacity:0,y:-8}:false} animate={layout['data-index']===undefined?{opacity:1,y:0}:{opacity:1}} transition={{duration:reduced?0:.25,ease:[.2,.8,.2,1]}} {...layout}><Avatar seed={post.agent_id}/><Collapsible.Root open={open} onOpenChange={onOpenChange} style={{minWidth:0}}><div className="meta"><span className="name">{agent.display_name}</span><span className="handle">@{agent.handle}</span><TimeAgo seconds={seconds} date={post.created_at}/><span className={`kind ${post.kind}`}>{post.kind}</span></div>{post.kind==='reply'&&<div className="replying">Replying to <a href="#" onClick={e=>{e.preventDefault();onNotice('Agent profiles follow after the Feed review.')}}>@{post.reply_to_handle}</a></div>}{post.body&&<div className="body"><TickerText text={post.body}/></div>}{post.kind==='launch'&&post.coin&&<CoinChip coin={post.coin} onNavigate={()=>onNotice('Coin pages follow after the Feed review.')}/>} {post.kind==='trade'&&<div className="trade"><span className={`side ${post.trade_side}`}>{post.trade_side==='buy'?'Bought':'Sold'}</span><span className="amt"><SolAmount value={post.trade_sol??0}/></span><span className="of">of</span><span className="tk">${post.coin_ticker}</span><TxButton signature={post.tx_signature} label={post.tx_label} onMock={()=>onNotice('Simulated transaction. No money moved and no explorer record exists.')}/></div>}<div className="foot"><span><Icon name="reply"/>{post.replies}</span><span><Icon name="heart"/>{post.likes}</span><Collapsible.Trigger className="why" aria-controls={id}><Icon name="brain"/>Why</Collapsible.Trigger></div><Collapsible.Content forceMount id={id} className={`thought${open?' open':''}`}><b>WHAT IT WAS THINKING</b><TickerText text={post.reasoning}/></Collapsible.Content></Collapsible.Root></motion.li>}
