'use client';
import {Fragment} from 'react';
import {Icon} from './icons';
import {config} from '../config';
export function hash(s:string){let h=2166136261;for(const c of s){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
const HUES=[262,212,168,32,340,12,190,288,48,142];
/** Signed bit shifts intentionally match the approved reference, including its black/blank shapes. */
export function Avatar({seed,size=40}:{seed:string;size?:number}){const h=hash(seed),a=HUES[h%10],b=HUES[(h>>4)%10],k=(h>>8)%4,r=(h>>12)%360;const fill=`hsl(${b} 70% 68%)`;const shapes=[<circle key="circle" cx={14+(h>>16)%12} cy={14+(h>>20)%12} r="11" fill={fill}/>,<rect key="rect" x="8" y="8" width="24" height="24" rx="6" transform={`rotate(${r} 20 20)`} fill={fill}/>,<path key="path" d={`M0 ${24+(h>>16)%10}L40 ${12+(h>>20)%10}V40H0z`} fill={fill}/>,<circle key="ring" cx="20" cy="20" r="9" fill="none" stroke={fill} strokeWidth="6"/>];return <svg className={`av${size===32?' av-md':size===24?' av-sm':''}`} width={size} height={size} viewBox="0 0 40 40" aria-hidden="true"><rect width="40" height="40" fill={`hsl(${a} 42% 30%)`}/>{shapes[k]}</svg>}
export function CoinImage({ticker,size=44}:{ticker:string;size?:number}){const h=hash(ticker);return <span className={`ci ci-${size}`} style={{background:`hsl(${HUES[h%10]} 38% ${26+(h>>5)%8}%)`}}>{ticker.slice(0,size<32?2:3)}</span>}
export function SolAmount({value}:{value:number}){return <>{value<1?value.toFixed(4):value.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})}<span className="sol">SOL</span></>}
export function TickerText({text}:{text:string}){return <>{text.split(/(\$[A-Z0-9]{2,10})/g).map((part,i)=>/^\$[A-Z0-9]+$/.test(part)?<span className="tk" key={i}>{part}</span>:<Fragment key={i}>{part}</Fragment>)}</>}
export function ProgressBar({value,mini=false}:{value:number;mini?:boolean}){return <div className={mini?'mini':'prog'}><div className="bar" role="progressbar" aria-label="Curve progress" aria-valuenow={value} aria-valuemin={0} aria-valuemax={100}><i style={{width:`${value}%`}}/></div><span>{value}%</span></div>}
export function TxButton({signature,label,onMock}:{signature?:string;label:string;onMock:()=>void}){return <a className="tx" href={signature?config.EXPLORER_TX.replace('{sig}',encodeURIComponent(signature)):undefined} role={signature?undefined:'button'} tabIndex={signature?undefined:0} target={signature?'_blank':undefined} rel={signature?'noopener noreferrer':undefined} title={signature?'View on Solscan':'Simulated transaction — no explorer record'} onClick={signature?undefined:onMock} onKeyDown={e=>{if(!signature&&(e.key==='Enter'||e.key===' ')){e.preventDefault();onMock()}}}>{label}<Icon name="ext"/></a>}
export function TimeAgo({seconds,date}:{seconds:number;date:number}){const label=seconds<60?`${seconds}s`:seconds<3600?`${Math.floor(seconds/60)}m`:seconds<86400?`${Math.floor(seconds/3600)}h`:`${Math.floor(seconds/86400)}d`;return <span className="time" title={new Date(date).toISOString()}>· {label}</span>}
