const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'/Users/blissssssss/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs/promises'),path=require('node:path');const {localRoute,root}=require('./capture-feed.cjs');
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});const results=[];
for(const [width,height,key]of [[1440,1000,'d'],[1100,900,'t'],[390,844,'m']]){
 const ref=await browser.newPage({viewport:{width,height},deviceScaleFactor:2});await ref.addInitScript(()=>window.setInterval=()=>0);await ref.goto('file://'+root+'/reference/stillwire-reference.html');await ref.evaluate(()=>document.fonts.ready);
 await ref.evaluate(key=>{feed.innerHTML=postHTML({...lines[0],ago:1,l:0,r:0},true)+seed.map(p=>postHTML(p)).join('');const labels=key==='d'?['wveT','n3qD','NBj3']:key==='t'?['3dD6','EYuz','demo']:['ekcK','t1Un','demo'];document.querySelectorAll('.tx').forEach((el,i)=>el.firstChild.textContent=labels[i]??'demo');if(key==='d'){Object.assign(C[1],{mc:44.79,p:53});Object.assign(C[3],{mc:27.23,p:32})}if(key==='t'){Object.assign(C[0],{mc:60.76,ch:18.2,p:72});Object.assign(C[1],{mc:43.84,ch:8.6,p:53})}if(key==='m')C[2].mc=39.9;renderMovers()},key);
 await ref.waitForTimeout(350);await ref.evaluate(()=>document.getAnimations().forEach(a=>{a.pause();a.currentTime=800}));await ref.screenshot({path:path.join(root,'review','html-reference-'+width+'.png')});
 const app=await browser.newPage({viewport:{width,height},deviceScaleFactor:2});await app.route('**/*',localRoute);await app.goto('http://stillwire.test/?review='+key);await app.waitForFunction(()=>document.querySelector('.post .name')?.textContent==='Ninth Gate');await app.evaluate(()=>document.fonts.ready);await app.waitForTimeout(350);await app.evaluate(()=>document.getAnimations().forEach(a=>{a.pause();a.currentTime=800}));await app.screenshot({path:path.join(root,'review','feed-'+width+'.png')});
 const metrics=()=>Object.fromEntries(['.shell','.main','.head','.post','.post:nth-child(2)','.post:nth-child(2) .body','.coin-chip','.mcard','.nav a','.panel','.wallet'].map(selector=>{const el=document.querySelector(selector),r=el.getBoundingClientRect(),s=getComputedStyle(el);return [selector,{x:r.x,y:r.y,width:r.width,height:r.height,fontSize:s.fontSize,fontWeight:s.fontWeight,lineHeight:s.lineHeight,font:s.fontFamily}]}));results.push({width,reference:await ref.evaluate(metrics),next:await app.evaluate(metrics)});await ref.close();await app.close();}
await fs.writeFile(path.join(root,'review','layout-metrics.json'),JSON.stringify(results,null,2));console.log(results.map(x=>({width:x.width,geometryMatches:Object.keys(x.reference).every(k=>['x','y','width','height'].every(p=>Math.abs(x.reference[k][p]-x.next[k][p])<.02))})));await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
